language: java

jdk:
  - oraclejdk8

before_script:
  - mkdir -p downloads
  - mkdir -p data
  - if [[ ! -d downloads/mongodb-linux-x86_64-ubuntu1604-${MONGO_VERSION} ]] ; then cd downloads && wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-${MONGO_VERSION}.tgz && tar xzf mongodb-linux-x86_64-ubuntu1604-${MONGO_VERSION}.tgz; fi
  - set PATH="downloads/mongodb-linux-x86_64-ubuntu1604-${MONGO_VERSION}/bin:$PATH"
  - mongod --version
  - mongod --dbpath data --replSet rs0 
  - sleep 20
  - |-
    mongo admin --eval  "db.adminCommand({setFeatureCompatibilityVersion: '3.4'});"
  - |-
    mongo --eval "rs.initiate({_id: 'rs0', members:[{_id: 0, host: '127.0.0.1:27017'}]});"
  - sleep 15

services:
  - mongodb

env:
  matrix:
    - PROFILE=ci
    - PROFILE=mongo36-next
 global:
    - MONGO_VERSION=3.7.9

addons:
  apt:
    - oracle-java8-installer

sudo: false

cache:
  directories:
    - $HOME/.m2

install:

script: "mvn clean dependency:list test -P${PROFILE} -Dsort"
